<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * employeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class employeeRepository extends EntityRepository
{
}
